// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.24;

import {ReceiverTemplate} from "./cre/ReceiverTemplate.sol";
import {CapacityMarket} from "./CapacityMarket.sol";
import {CapacityPool} from "./CapacityPool.sol";

/// @title CREDeadlineReceiver
/// @notice The onchain half of MUSTER's Chainlink CRE integration: a CRE
/// workflow watches `CapacityMarket`/`CapacityPool` for positions whose
/// `activationDeadline`/`disputeDeadline` has passed, and periodically
/// submits a report naming which of the six already-permissionless deadline
/// functions to call and on which id. The Chainlink DON-operated
/// `KeystoneForwarder` delivers that report here via `onReport`.
///
/// Extends `ReceiverTemplate` (`src/cre/ReceiverTemplate.sol`) — vendored
/// verbatim from the official `keeper-bot-ts` CRE template generated by
/// `cre init` against a real, authenticated Chainlink account, not
/// reconstructed from a paraphrase of the docs — rather than reimplementing
/// `IReceiver` from scratch. That gets this contract the sponsor's own
/// forwarder-address validation (updatable post-deployment via `Ownable`,
/// in case Chainlink ever rotates the Forwarder) and optional
/// workflow-author/name/id pinning for free, instead of a bespoke,
/// unaudited-by-anyone-but-us version of the same check.
///
/// On top of that template, this contract is deliberately a **closed
/// dispatcher, not a generic relayer**: `_processReport` cannot be made to
/// carry arbitrary `(target, calldata)` — only one of six named `Action`s
/// against one of two fixed, immutable contract addresses set at
/// deployment. This is a narrower, safer surface than "forward whatever
/// calldata the report contains," and it costs nothing here because the six
/// targets are a closed, known set: every function this contract can ever
/// call is already callable by literally anyone today (that is the entire
/// point of them being permissionless). Spoofing a call to this receiver
/// directly (bypassing the Forwarder — blocked by `ReceiverTemplate`'s own
/// check, but suppose it weren't) grants an attacker nothing beyond what
/// they could already do by calling `claimDefault` etc. themselves — there
/// is no privilege escalation here, only convenience and reliability.
contract CREDeadlineReceiver is ReceiverTemplate {
    enum Action {
        MarketClaimDefault,
        MarketFinalizeDelivery,
        MarketResolveDisputeByTimeout,
        PoolClaimAssignmentDefault,
        PoolFinalizeAssignmentDelivery,
        PoolResolveAssignmentDisputeByTimeout
    }

    /// @param id `positionId` for the three `Market*` actions, `reservationId`
    /// for the three `Pool*` actions.
    /// @param subId `assignmentIndex` for `Pool*` actions; ignored (but still
    /// present, always `0` in practice) for `Market*` actions — kept as a
    /// fixed-shape struct rather than two differently-shaped variants so the
    /// workflow can encode a single `DeadlineAction[]` regardless of which
    /// contract each entry targets.
    struct DeadlineAction {
        Action action;
        uint256 id;
        uint256 subId;
    }

    CapacityMarket public immutable market;
    CapacityPool public immutable pool;

    /// @notice One event per attempted action, win or lose. A `false`
    /// `success` is expected and routine — e.g. someone else already called
    /// the same deadline function first, or the position moved on before
    /// this batch executed — not a sign anything is wrong with this
    /// contract or the workflow.
    event ActionAttempted(uint256 indexed batchIndex, Action action, uint256 id, uint256 subId, bool success);

    constructor(address forwarder_, address market_, address pool_) ReceiverTemplate(forwarder_) {
        market = CapacityMarket(market_);
        pool = CapacityPool(pool_);
    }

    /// @notice `ReceiverTemplate.onReport` already verified `msg.sender ==`
    /// the configured forwarder (and any configured workflow-identity
    /// pinning) before calling this — see that contract for the exact
    /// checks. This function only decodes and dispatches; it performs no
    /// access control of its own because `ReceiverTemplate` already did.
    function _processReport(bytes calldata report) internal override {
        DeadlineAction[] memory actions = abi.decode(report, (DeadlineAction[]));
        for (uint256 i = 0; i < actions.length; i++) {
            bool ok = _attempt(actions[i]);
            emit ActionAttempted(i, actions[i].action, actions[i].id, actions[i].subId, ok);
        }
    }

    /// @notice Each action is attempted independently so one stale or
    /// already-resolved entry in a batch never blocks the rest — the same
    /// honest-degradation principle the rest of this project applies to
    /// partial failures (a timed-out assignment's default not blocking a
    /// sibling's settlement, etc.).
    function _attempt(DeadlineAction memory a) private returns (bool ok) {
        if (a.action == Action.MarketClaimDefault) {
            try market.claimDefault(a.id) {
                ok = true;
            } catch {
                ok = false;
            }
        } else if (a.action == Action.MarketFinalizeDelivery) {
            try market.finalizeDelivery(a.id) {
                ok = true;
            } catch {
                ok = false;
            }
        } else if (a.action == Action.MarketResolveDisputeByTimeout) {
            try market.resolveDisputeByTimeout(a.id) {
                ok = true;
            } catch {
                ok = false;
            }
        } else if (a.action == Action.PoolClaimAssignmentDefault) {
            try pool.claimAssignmentDefault(a.id, a.subId) {
                ok = true;
            } catch {
                ok = false;
            }
        } else if (a.action == Action.PoolFinalizeAssignmentDelivery) {
            try pool.finalizeAssignmentDelivery(a.id, a.subId) {
                ok = true;
            } catch {
                ok = false;
            }
        } else if (a.action == Action.PoolResolveAssignmentDisputeByTimeout) {
            try pool.resolveAssignmentDisputeByTimeout(a.id, a.subId) {
                ok = true;
            } catch {
                ok = false;
            }
        }
    }
}
